app = "gitty-api"
primary_region = "iad"

[build]
dockerfile = "Dockerfile"

[env]
ENVIRONMENT = "production"
CHROMA_PERSIST_DIR = "/data/chroma"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8_000
min_machines_running = 0
processes = [ "app" ]

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "2gb"

[[vm.mounts]]
source = "chroma_data"
destination = "/data/chroma"
